version: '3.1'
services:
  stats-server:
    build: stat-server/server
    image: stat
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/hit

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=hit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm-server
    image: ewm-server-main
    container_name: ewm-service-main
    ports:
      - "8080:8080"
    depends_on:
#      - stats-server
      - ewm-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres