DROP TABLE IF EXISTS hits;
CREATE TABLE IF NOT EXISTS hits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app         VARCHAR(128),
    uri         VARCHAR(128),
    ip          VARCHAR(32),
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT hit_pk PRIMARY KEY (id)
    );